language: go
sudo: required

services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$QUAY_PASSWORD" | docker login -u "$QUAY_USERNAME" --password-stdin quay.io
  - make docker.io/vdemeester/kobw-builder
  - make quay.io/vdemeest/kobw-builder
  - ./hack/push.sh
